name: app

services:
  api-service:
    build:
      context: .
      dockerfile: Dockerfile

    restart: always

    deploy:
      replicas: 2

    labels:
      - traefik.enable=true

      - traefik.http.routers.api.rule=Host(`shubhamlearningvps.online`)
      - traefik.http.routers.api.entrypoints=websecure

      - traefik.http.routers.api.tls=true
      - traefik.http.routers.api.tls.certresolver=letsencrypt

      - traefik.http.services.api.loadbalancer.server.port=8080

      - traefik.docker.network=traefik-network

    networks:
      - traefik-network

networks:
  traefik-network:
    external: true